---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: latest

inputs:
- name: repository

outputs:
- name: out

run:
  path: tasks/deploy-image.sh
  dir: repository
